name: nexo_app
description: "NEXO social/gaming prototype"
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  http: ^1.6.0
  web_socket_channel: ^3.0.3
  flutter_secure_storage: ^10.3.4
  flutter_webrtc: ^1.6.2+hotfix.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - crown_shine.png
    - diamond_glow.png
    - fire_wings.png
    - galaxy_aura.png
    - name_glow_ticket.png
    - neon_heart.png
    - rainbow_ticket.png
    - shadow_flame.png
    - vip_emblem.png