const {randomBytes}=require("crypto");
function b(req){return req.body&&typeof req.body==="object"?req.body:{};}
function send(reply,status,data){return reply.code(status).send(data);}
function uid(req){return req.user.sub;}
const INITIAL='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';
function code(){return randomBytes(4).toString('hex').slice(0,6).toUpperCase();}
function color(p){return p?p===p.toUpperCase()?'white':'black':null;}
function parse(fen){const p=String(fen||INITIAL).trim().split(/\s+/),board=new Array(64).fill(null);let i=0;for(const ch of p[0]){if(ch==='/')continue;if(ch>='1'&&ch<='8')i+=Number(ch);else board[i++]=ch;}return{board,turn:p[1]==='b'?'black':'white',castling:p[2]&&p[2]!=='-'?p[2]:'',ep:p[3]&&p[3]!=='-'?p[3]:null,half:Number(p[4]||0),full:Number(p[5]||1)};}
function sq(s){s=String(s||'').toLowerCase();return/^[a-h][1-8]$/.test(s)?(8-Number(s[1]))*8+s.charCodeAt(0)-97:-1;}
function name(i){return String.fromCharCode(97+i%8)+(8-Math.floor(i/8));}
function bounds(r,c){return r>=0&&r<8&&c>=0&&c<8;}
function attacked(st,target,by){const tr=Math.floor(target/8),tc=target%8,ww=by==='white';for(let i=0;i<64;i++){const p=st.board[i];if(!p||color(p)!==by)continue;const r=Math.floor(i/8),c=i%8,t=p.toLowerCase();if(t==='p'){const dr=ww?-1:1;if((r+dr===tr)&&((c-1===tc)||(c+1===tc)))return true;}else if(t==='n'){for(const x of [[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]])if(r+x[0]===tr&&c+x[1]===tc)return true;}else if(t==='k'){if(Math.max(Math.abs(tr-r),Math.abs(tc-c))===1)return true;}else{const ds=[];if(t==='b'||t==='q')ds.push([-1,-1],[-1,1],[1,-1],[1,1]);if(t==='r'||t==='q')ds.push([-1,0],[1,0],[0,-1],[0,1]);for(const [dr,dc] of ds){let rr=r+dr,cc=c+dc;while(bounds(rr,cc)){const idx=rr*8+cc;if(idx===target)return true;if(st.board[idx])break;rr+=dr;cc+=dc;}}}}return false;}
function king(st,c){return st.board.findIndex(p=>p===(c==='white'?'K':'k'));}
function inCheck(st,c){const k=king(st,c);return k>=0&&attacked(st,k,c==='white'?'black':'white');}
function clone(st){return{board:st.board.slice(),turn:st.turn,castling:st.castling,ep:st.ep,half:st.half,full:st.full};}
function add(out,from,to,prom,flags){out.push({from,to,promotion:prom||null,castle:!!flags?.castle,ep:!!flags?.ep});}
function pseudo(st){const out=[],w=st.turn==='white';for(let i=0;i<64;i++){const p=st.board[i];if(!p||color(p)!==st.turn)continue;const r=Math.floor(i/8),c=i%8,t=p.toLowerCase();if(t==='p'){const dir=w?-1:1,start=w?6:1,promo=w?0:7,rr=r+dir;if(bounds(rr,c)&&!st.board[rr*8+c]){const to=rr*8+c;if(rr===promo)for(const x of ['q','r','b','n'])add(out,i,to,x);else add(out,i,to);const rr2=r+2*dir;if(r===start&&!st.board[rr2*8+c])add(out,i,rr2*8+c);}for(const dc of [-1,1]){const r2=r+dir,c2=c+dc;if(!bounds(r2,c2))continue;const to=r2*8+c2,target=st.board[to];if(target&&color(target)!==st.turn){if(r2===promo)for(const x of ['q','r','b','n'])add(out,i,to,x);else add(out,i,to);}else if(st.ep===name(to))add(out,i,to,null,{ep:true});}}else if(t==='n'){for(const [dr,dc] of [[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]]){const rr=r+dr,cc=c+dc;if(!bounds(rr,cc))continue;const q=st.board[rr*8+cc];if(!q||color(q)!==st.turn)add(out,i,rr*8+cc);}}else if(t==='b'||t==='r'||t==='q'){const ds=[];if(t==='b'||t==='q')ds.push([-1,-1],[-1,1],[1,-1],[1,1]);if(t==='r'||t==='q')ds.push([-1,0],[1,0],[0,-1],[0,1]);for(const [dr,dc] of ds){let rr=r+dr,cc=c+dc;while(bounds(rr,cc)){const to=rr*8+cc,q=st.board[to];if(!q)add(out,i,to);else{if(color(q)!==st.turn)add(out,i,to);break;}rr+=dr;cc+=dc;}}}else if(t==='k'){for(const [dr,dc] of [[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]]){const rr=r+dr,cc=c+dc;if(!bounds(rr,cc))continue;const q=st.board[rr*8+cc];if(!q||color(q)!==st.turn)add(out,i,rr*8+cc);}const e=w?'black':'white';if(w&&i===60&&!inCheck(st,'white')){if(st.castling.includes('K')&&!st.board[61]&&!st.board[62]&&!attacked(st,61,e)&&!attacked(st,62,e))add(out,60,62,null,{castle:true});if(st.castling.includes('Q')&&!st.board[59]&&!st.board[58]&&!st.board[57]&&!attacked(st,59,e)&&!attacked(st,58,e))add(out,60,58,null,{castle:true});}if(!w&&i===4&&!inCheck(st,'black')){if(st.castling.includes('k')&&!st.board[5]&&!st.board[6]&&!attacked(st,5,e)&&!attacked(st,6,e))add(out,4,6,null,{castle:true});if(st.castling.includes('q')&&!st.board[3]&&!st.board[2]&&!st.board[1]&&!attacked(st,3,e)&&!attacked(st,2,e))add(out,4,2,null,{castle:true});}}}return out;}
function apply(st,m){const n=clone(st),p=n.board[m.from],cap=n.board[m.to],pawn=p&&p.toLowerCase()==='p';n.board[m.from]=null;if(m.ep)n.board[m.to+(p==='P'?8:-8)]=null;let placed=p;if(m.promotion)placed=p==='P'?m.promotion.toUpperCase():m.promotion;n.board[m.to]=placed;if(m.castle){if(m.to===62){n.board[63]=null;n.board[61]='R';}if(m.to===58){n.board[56]=null;n.board[59]='R';}if(m.to===6){n.board[7]=null;n.board[5]='r';}if(m.to===2){n.board[0]=null;n.board[3]='r';}}let rights=n.castling;if(p==='K')rights=rights.replace('K','').replace('Q','');if(p==='k')rights=rights.replace('k','').replace('q','');if(m.from===63||m.to===63)rights=rights.replace('K','');if(m.from===56||m.to===56)rights=rights.replace('Q','');if(m.from===7||m.to===7)rights=rights.replace('k','');if(m.from===0||m.to===0)rights=rights.replace('q','');n.castling=rights;n.ep=null;if(pawn&&Math.abs(m.to-m.from)===16)n.ep=name((m.to+m.from)/2);n.half=pawn||cap||m.ep?0:n.half+1;if(st.turn==='black')n.full++;n.turn=st.turn==='white'?'black':'white';return n;}
function legal(st){const o=[];for(const m of pseudo(st)){const n=apply(st,m);if(!inCheck(n,st.turn))o.push(m);}return o;}
function uci(m){return name(m.from)+name(m.to)+(m.promotion||'');}
function fen(st){const rows=[];for(let r=0;r<8;r++){let row='',e=0;for(let c=0;c<8;c++){const p=st.board[r*8+c];if(!p)e++;else{if(e){row+=e;e=0;}row+=p;}}if(e)row+=e;rows.push(row);}return rows.join('/')+' '+(st.turn==='white'?'w':'b')+' '+(st.castling||'-')+' '+(st.ep||'-')+' '+st.half+' '+st.full;}
async function view(q,id){const r=await q("SELECT * FROM nexo.chess_rooms WHERE id=$1",[id]);if(!r.rowCount)return null;const x=r.rows[0],ps=await q("SELECT p.user_id AS \"userId\",u.username,u.display_name AS \"displayName\",u.avatar,p.color,p.ready FROM nexo.chess_room_players p JOIN nexo.users u ON u.id=p.user_id WHERE p.room_id=$1 ORDER BY CASE WHEN p.color='white' THEN 0 ELSE 1 END",[id]);return{id:x.id,inviteCode:x.invite_code,hostId:x.host_id,status:x.status,turnColor:x.turn_color,fen:x.fen,winnerUserId:x.winner_user_id,drawReason:x.draw_reason,moves:Array.isArray(x.moves)?x.moves:[],players:ps.rows};}
async function registerChess(app,auth,q){const guard=(req,reply)=>auth(req,reply);
 app.post("/games/chess/rooms",{preHandler:guard},async(req,reply)=>{const r=await q("INSERT INTO nexo.chess_rooms(invite_code,host_id,status,turn_color,fen,white_user_id) VALUES($1,$2,'waiting','white',$3,$2) RETURNING id",[code(),uid(req),INITIAL]);await q("INSERT INTO nexo.chess_room_players(room_id,user_id,color,ready) VALUES($1,$2,'white',false)",[r.rows[0].id,uid(req)]);return view(q,r.rows[0].id);});
 app.post("/games/chess/match",{preHandler:guard},async(req,reply)=>{const w=await q("SELECT r.id FROM nexo.chess_rooms r WHERE r.status='waiting' AND r.host_id<>$1 ORDER BY r.created_at LIMIT 1",[uid(req)]);if(!w.rowCount){const r=await q("INSERT INTO nexo.chess_rooms(invite_code,host_id,status,turn_color,fen,white_user_id) VALUES($1,$2,'waiting','white',$3,$2) RETURNING id",[code(),uid(req),INITIAL]);await q("INSERT INTO nexo.chess_room_players(room_id,user_id,color,ready) VALUES($1,$2,'white',false)",[r.rows[0].id,uid(req)]);return view(q,r.rows[0].id);}const id=w.rows[0].id;const c=await q("SELECT COUNT(*)::int AS n FROM nexo.chess_room_players WHERE room_id=$1",[id]);if(Number(c.rows[0].n)>=2)return send(reply,409,{error:"CHESS_ROOM_FULL"});await q("INSERT INTO nexo.chess_room_players(room_id,user_id,color,ready) VALUES($1,$2,'black',false)",[id,uid(req)]);await q("UPDATE nexo.chess_rooms SET black_user_id=$1 WHERE id=$2",[uid(req),id]);return view(q,id);});
 app.post("/games/chess/rooms/:id/join",{preHandler:guard},async(req,reply)=>{const r=await q("SELECT * FROM nexo.chess_rooms WHERE id::text=$1 OR upper(invite_code)=upper($1) LIMIT 1",[req.params.id]);if(!r.rowCount)return send(reply,404,{error:"CHESS_ROOM_NOT_FOUND"});const x=r.rows[0];if(String(x.host_id)===String(uid(req))||String(x.black_user_id||"")===String(uid(req)))return view(q,x.id);if(x.status!=="waiting")return send(reply,409,{error:"CHESS_ROOM_FULL"});await q("INSERT INTO nexo.chess_room_players(room_id,user_id,color,ready) VALUES($1,$2,'black',false)",[x.id,uid(req)]);await q("UPDATE nexo.chess_rooms SET black_user_id=$1 WHERE id=$2",[uid(req),x.id]);return view(q,x.id);});
 app.post("/games/chess/rooms/:id/ready",{preHandler:guard},async(req,reply)=>{const r=await q("UPDATE nexo.chess_room_players SET ready=$1 WHERE room_id=$2 AND user_id=$3",[b(req).ready!==false,req.params.id,uid(req)]);if(!r.rowCount)return send(reply,404,{error:"CHESS_NOT_IN_ROOM"});return view(q,req.params.id);});
 app.post("/games/chess/rooms/:id/start",{preHandler:guard},async(req,reply)=>{const r=await q("SELECT host_id FROM nexo.chess_rooms WHERE id=$1",[req.params.id]);if(!r.rowCount)return send(reply,404,{error:"CHESS_ROOM_NOT_FOUND"});if(String(r.rows[0].host_id)!==String(uid(req)))return send(reply,403,{error:"CHESS_HOST_ONLY"});const ps=await q("SELECT COUNT(*)::int AS n,COUNT(*) FILTER(WHERE ready)::int AS ready FROM nexo.chess_room_players WHERE room_id=$1",[req.params.id]);if(Number(ps.rows[0].n)!==2||Number(ps.rows[0].ready)!==2)return send(reply,409,{error:"CHESS_NEEDS_TWO_READY"});await q("UPDATE nexo.chess_rooms SET status='playing',turn_color='white' WHERE id=$1",[req.params.id]);return view(q,req.params.id);});
 app.post("/games/chess/rooms/:id/move",{preHandler:guard},async(req,reply)=>{const id=req.params.id,r=await q("SELECT * FROM nexo.chess_rooms WHERE id=$1",[id]);if(!r.rowCount)return send(reply,404,{error:"CHESS_ROOM_NOT_FOUND"});const x=r.rows[0];if(x.status!=="playing")return send(reply,409,{error:"CHESS_NOT_PLAYING"});const me=await q("SELECT color FROM nexo.chess_room_players WHERE room_id=$1 AND user_id=$2",[id,uid(req)]);if(!me.rowCount)return send(reply,403,{error:"CHESS_NOT_IN_ROOM"});const c=me.rows[0].color;if(c!==x.turn_color)return send(reply,409,{error:"CHESS_NOT_YOUR_TURN"});const mv=String(b(req).uci||"").toLowerCase();if(!/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(mv))return send(reply,400,{error:"CHESS_INVALID_UCI"});const st=parse(x.fen),m=legal(st).find(z=>uci(z)===mv);if(!m)return send(reply,409,{error:"CHESS_ILLEGAL_MOVE"});const n=apply(st,m),moves=Array.isArray(x.moves)?x.moves.slice():[];moves.push(mv);const ls=legal(n);let status='playing',winnerUserId=null,drawReason=null;if(!ls.length){if(inCheck(n,n.turn)){status='finished';winnerUserId=uid(req);}else{status='finished';drawReason='stalemate';}}else if(n.half>=100){status='finished';drawReason='fifty_move';}await q("UPDATE nexo.chess_rooms SET fen=$1,turn_color=$2,status=$3,winner_user_id=$4,draw_reason=$5,moves=$6::jsonb,updated_at=NOW() WHERE id=$7",[fen(n),n.turn,status,winnerUserId,drawReason,JSON.stringify(moves),id]);return view(q,id);});
 app.get("/games/chess/rooms/:id",{preHandler:guard},async(req,reply)=>{const r=await q("SELECT host_id,black_user_id,white_user_id FROM nexo.chess_rooms WHERE id=$1",[req.params.id]);if(!r.rowCount)return send(reply,404,{error:"CHESS_ROOM_NOT_FOUND"});if(String(r.rows[0].host_id)!==String(uid(req))&&String(r.rows[0].black_user_id||"")!==String(uid(req))&&String(r.rows[0].white_user_id||"")!==String(uid(req)))return send(reply,403,{error:"CHESS_NOT_IN_ROOM"});return view(q,req.params.id);});
}
module.exports={registerChess};